var express = require('express');
var router = express.Router();
var authenticateToken = require('../middleware/authAuto');
var autoController = require('../controllers/autoControllerMod');

router.get('/minden', autoController.osszes);
router.get('/egy/:id', autoController.egy);
router.delete('/torol/:id', autoController.torol);
router.get('/marka', autoController.getMarka);
router.get('/szin', autoController.getSzin);
router.get('/uzemanyag', autoController.getUzemanyag);
router.post('/szuro', autoController.szuro);
router.post('/login', autoController.login);
router.post('/regisztracio',autoController.regisztracio);
router.get('/valtok', autoController.getValto);
router.get('/ajtok', autoController.getAjto);
router.get('/szemelyek', autoController.getSzemely);
router.get('/count', autoController.getCount);
router.post('/refresh', autoController.refresh);
router.get('/profil',authenticateToken,autoController.profil);
router.post('/logout', autoController.logout);
router.get('/felhasznalok', authenticateToken, autoController.felhasznalok);
router.get('/ajanlott/:marka', autoController.ajanlott);
router.post('/erdekel', authenticateToken, autoController.erdekel);
router.get('/erdekeltek', authenticateToken, autoController.erdekeltek);
router.put('/profilmodosit', authenticateToken, autoController.felhasznaloModositas);
router.put('/jelszomodositas', authenticateToken, autoController.jelszoModositas);
router.post('/uzenet', authenticateToken, autoController.uzenetKuldes);
router.get('/uzenetek', authenticateToken, autoController.uzenetekLekerdezese);
router.post('/adminuzenetek', authenticateToken, autoController.AdminUzenetek);
router.get('/chatablak', authenticateToken, autoController.ChatAblak);
router.post('/admin/chatablak', authenticateToken, autoController.ChatAblakAdmin);
router.post('/felhasznalo/chatablak', authenticateToken, autoController.ChatAblakFelhasznalo);
router.get('/szamla', authenticateToken, autoController.szamlaAdatok);
router.get('/random',autoController.randomautok);
router.put('/szerkesztes/:id',authenticateToken,autoController.Szerkesztes);
router.post('/ujauto',authenticateToken,autoController.UjAuto);

module.exports = router;
