var express = require('express');
var router = express.Router();
var authenticateToken = require('../middleware/authAuto');
var autoController = require('../controllers/autoControllerMod');

router.get('/minden', autoController.osszes);
router.get('/egy/:id', autoController.egy);
router.post('/hozzad', autoController.hozzaad);
router.put('/modosit/:id', autoController.modosit);
router.delete('/torol/:id', autoController.torol);
router.get('/marka', autoController.getMarka);
router.get('/szin', autoController.getSzin);
router.get('/uzemanyag', autoController.getUzemanyag);
router.post('/szuro', autoController.szuro);
router.post('/login', autoController.login);
router.post('/regisztracio',autoController.regisztracio);
router.get('/valtok', autoController.getValto);
router.get('/ajtok', autoController.getAjto);
router.get('/szemelyek', autoController.getSzemely);
router.get('/count', autoController.getCount);
router.post('/refresh', autoController.refresh);
router.get('/profil',authenticateToken,autoController.profil);
router.post('/logout', autoController.logout);
router.get('/felhasznalok', authenticateToken, autoController.felhasznalok);
module.exports = router;
